---
# =============================================================================
# Общие переменные для всех хостов
# Переопределяют defaults только при необходимости
# =============================================================================

# VPN клиент (sing-box не поддерживает XHTTP, используем xray)
vpn_local_client: xray

# Исключить сервисы из VPN роутинга
vpn_services_exclude:
  - kinovod
  - telegram
